### ISSUE TITLE
Problems creating a development installation for CellProfiler

### ISSUE THREAD

**Issue by GenevieveBuckley** [CellProfiler/CellProfiler#4346]
**Describe the bug**
I'm running into some problems setting up a CellProfiler development environment. It's possible I might have become confused by the instructions in the docs, or am looking at slightly out of date information. Any tips would be appreciated!

May be similar to https://github.com/CellProfiler/CellProfiler/issues/4340

**To Reproduce**
1.. Fork and clone the CellProfiler repository, then change directory into it
```
git clone git@github.com:CellProfiler/CellProfiler.git
cd CellProfiler
```

2. Create a new conda environment using this `environment.yml` file
```
name: cellprofiler-dev
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults

dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pandas
  - mysqlclient
  - openjdk
  - gtk2
  - wxpython
 ```

3. Activate the new environment with `conda activate cellprofiler-dev`

4. Pip install CellProfiler with `pip install -e .`

5. Try to launch cellprofiler from the terminal by typing the command `cellprofiler`

**Expected behavior**
I expected the main CellProfiler window to open.

**Actual behavior**
Instead of the expected behaviour, I saw this error message
```python-traceback

Traceback (most recent call last):
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/bin/cellprofiler", line 33, in <module>
    sys.exit(load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')())
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/bin/cellprofiler", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/__main__.py", line 13, in <module>
    import bioformats.formatreader
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/site-packages/javabridge/jutil.py", line 162, in <module>
    import javabridge._javabridge as _javabridge
  File "_javabridge.pyx", line 1, in init _javabridge
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CellProfiler master branch version, from cloned local repository
 - Downloaded from the website or installed from source? Installed from source
 - If the latter, how? See the steps to reproduce above

**Additional context**
Here's the `conda list` of my environment (expand details below)

<details>
<summary>Details:</summary>

```

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
boto3                     1.17.4                   pypi_0    pypi
botocore                  1.20.4                   pypi_0    pypi
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h7979940_1007    conda-forge
cellprofiler              4.0.7                     dev_0    <develop>
cellprofiler-core         4.0.7                    pypi_0    pypi
centrosome                1.2.0                    pypi_0    pypi
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.4           py38ha65f79e_1    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
cryptography              3.3.1            py38h2b97feb_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
expat                     2.2.10               h9c3ff4c_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gdk-pixbuf                2.42.2               h0c95a7a_2    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.6               h9c3ff4c_3    conda-forge
glib-tools                2.66.6               h9c3ff4c_3    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.3               h3560a44_0    conda-forge
gtk2                      2.24.33              hab0c2f8_0    conda-forge
h5py                      2.10.0                   pypi_0    pypi
harfbuzz                  2.7.4                h5cf4720_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imageio                   2.9.0                    pypi_0    pypi
inflect                   5.0.2                    pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.0.0                    pypi_0    pypi
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.0.1          default_ha53f305_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.6               h1f3bc88_3    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm11                 11.0.1               hf817b99_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mahotas                   1.4.11                   pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.3                    pypi_0    pypi
mysql-common              8.0.22               ha770c72_3    conda-forge
mysql-libs                8.0.22               h935591d_3    conda-forge
mysqlclient               1.4.6                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                      pypi_0    pypi
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.61                 hb5efdd6_0    conda-forge
numpy                     1.19.3                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.1            py38h51da96c_0    conda-forge
pango                     1.42.4               h69149e4_5    conda-forge
pathlib2                  2.3.5            py38h578d9bd_3    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    8.1.0            py38ha0e1e83_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
prokaryote                2.4.2                    pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyqt                      5.12.3           py38h578d9bd_7    conda-forge
pyqt-impl                 5.12.3           py38h7400c14_7    conda-forge
pyqt5-sip                 4.19.18          py38h709712a_7    conda-forge
pyqtchart                 5.12             py38h7400c14_7    conda-forge
pyqtwebengine             5.12.1           py38h7400c14_7    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.6           hffdb5ce_5_cpython    conda-forge
python-bioformats         4.0.0                    pypi_0    pypi
python-dateutil           2.8.1                      py_0    conda-forge
python-javabridge         4.0.0                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     18.0.1                   pypi_0    pypi
qt                        5.12.9               h9d6b050_2    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
s3transfer                0.3.4                    pypi_0    pypi
scikit-image              0.18.1                   pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
sentry-sdk                0.18.0                   pypi_0    pypi
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2021.2.1                 pypi_0    pypi
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wxpython                  4.1.0            py38h2a0d1f2_4    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge

```

</details>

**Comment by GenevieveBuckley** [comment]
Things I tried to fix this: `pip install numpy==1.19.3 --no-cache-dir --no-binary :all:`

Someone suggested this for a sort of similar problem on stack overflow, so I tried it but it didn't seem to help.

**Comment by GenevieveBuckley** [comment]
I'm pretty sure I have the Java dependencies CellProfiler relies on (I didn't install anything new here, Ubuntu 20.04 seems to already come with java so all I did was make a new `JAVA_HOME` variable).
```
(base) genevieve@genevieve-G5-5500:~/GitHub/cellprofiler$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
(base) genevieve@genevieve-G5-5500:~/GitHub/cellprofiler$ echo $JAVA_HOME
/usr/bin/java
```
I think the problem is some kind of incompatibility affecting javabridge. I hit the same error in this environment if I start python and try to import javabridge.
```python
(base) genevieve@genevieve-G5-5500:~$ conda activate cellprofiler-dev
(cellprofiler-dev) genevieve@genevieve-G5-5500:~$ python
Python 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:21:18) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import javabridge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/site-packages/javabridge/jutil.py", line 162, in <module>
    import javabridge._javabridge as _javabridge
  File "_javabridge.pyx", line 1, in init _javabridge
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
>>> 
```

Making a new conda environment and only doing `pip install python-javabridge` does not result in the same problem. I can start python and import javabridge there just fine. This is why I think there's something odd/incompatible about the dependencies in my `cellprofiler-dev` conda environment.

I'm not deeply knowledgeable about javabridge, any guidance is very welcome.

**Comment by bethac07** [comment]
Can you try pinning your javabridge in your conda environment, so that numpy is definitely at 1.19.3 when javabridge is installed? Sometimes we see that error when a later version of numpy gets installed (say 1.20), then javabridge gets installed, and then numpy gets downgraded to 1.19.

**Comment by GenevieveBuckley** [comment]
I can try that. What version of javabridge should I be pinning it to?

**Comment by GenevieveBuckley** [comment]
Found it, I should pin `python-javabridge==4.0.0`

https://github.com/CellProfiler/CellProfiler/blob/9544bf5880eba004d2d588898213556f4dab28bf/setup.py#L81

**Comment by GenevieveBuckley** [comment]
This thread seems useful https://github.com/LeeKamentsky/python-javabridge/issues/152

**Comment by GenevieveBuckley** [comment]
I think I'm getting slightly closer.

```
conda create -n javabridge-test python=3.8 pip
conda activate javabridge-test
conda install wxPython
conda install python-javabridge
cd CellProfiler
# Edit line 79 of CellProfiler's setup.py to read "numpy==1.20.0" instead of "numpy==1.19.3"
python -m pip install -e .
```
Then I can start python and import javabridge and wx with no problems. But when I try and launch the CellProfiler window, I get this error:
```
(javabridge-test) genevieve@genevieve-G5-5500:~/GitHub/cellprofiler$ cellprofiler
Gtk-Message: 18:02:59.865: Failed to load module "atk-bridge"
Gtk-Message: 18:02:59.867: Failed to load module "canberra-gtk-module"
18:03:00: Debug: Adding duplicate image handler for 'Windows bitmap file'
18:03:00: Debug: Adding duplicate animation handler for '1' type
18:03:00: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/gui/app.py", line 69, in OnInit
    from .cpframe import CPFrame
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/gui/cpframe.py", line 25, in <module>
    from ._welcome_frame import WelcomeFrame
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/gui/_welcome_frame.py", line 7, in <module>
    import wx.html2
  File "/home/genevieve/anaconda3/envs/javabridge-test/lib/python3.8/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory
OnInit returned false, exiting...
```

I think if I can figure out the missing "atk-bridge" and "canberra-gtk-module" that might help.

**Comment by GenevieveBuckley** [comment]
In case anyone is curious, the reason I did it that way (with conda installs of wxPython and python-javabridge before pip installing an editable CellProfiler installation) is because otherwise pip would get stuck on wxPython.

**Comment by bethac07** [comment]
Ugh, my previous comment I was dumb, I meant pinning NUMPY (to 1.19.3).  Sorry, that's what I get for responding to stuff before being properly caffeinated.  

In any case, it looks like your new error is related to not having libwebkit, which is [required for CP4 on Ubuntu 20](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04)

**Comment by GenevieveBuckley** [comment]
I did try pinning numpy to 1.19.3 but I just could not get javabridge to work well with anything other than numpy 1.20

Agree re: libwebkit, will try and fix that today

**Comment by GenevieveBuckley** [comment]
Ok, I've fixed my missing libwebkit [by following these instructions](https://github.com/subgraph/Vega/issues/177#issuecomment-583778551)

> Open terminal and write this:
>
> 1. `sudo nano /etc/apt/sources.list`
> 2. Add this entry to the file and save: `deb http://cz.archive.ubuntu.com/ubuntu bionic main universe`
> 3. sudo apt-get update
> 4. sudo apt-get install libwebkitgtk-1.0-0

But it seems there's still something wrong. I am able to start python and import wx and javabridge, but when I call `cellprofiler` from the command line, I see this error:


```
Gtk-Message: 12:33:57.956: Failed to load module "atk-bridge"
Gtk-Message: 12:33:57.957: Failed to load module "canberra-gtk-module"
12:33:58: Debug: Adding duplicate image handler for 'Windows bitmap file'
12:33:58: Debug: Adding duplicate animation handler for '1' type
12:33:58: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/gui/app.py", line 69, in OnInit
    from .cpframe import CPFrame
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/gui/cpframe.py", line 36, in <module>
    from .pipelinecontroller import PipelineController
  File "/home/genevieve/GitHub/cellprofiler/cellprofiler/gui/pipelinecontroller.py", line 94, in <module>
    from cellprofiler_core.pipeline.io._v6 import load
ImportError: cannot import name 'load' from 'cellprofiler_core.pipeline.io._v6' (/home/genevieve/anaconda3/envs/cellprofiler-dev/lib/python3.8/site-packages/cellprofiler_core/pipeline/io/_v6.py)
OnInit returned false, exiting...
```

The `cellprofiler_core` version being used is 4.0.7 (this is what was pinned in the main cellprofiler `setup.py`, so this is expected).

>>> import cellprofiler_core.pipeline.io._v6
>>> dir(cellprofiler_core.pipeline.io._v6)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'dump']

I do see a `load` function in the master branch version of `cellprofiler_core`, so I'm going to try installing that instead next.

**Comment by GenevieveBuckley** [comment]
Yep, upgrading from `cellprofiler-core` 4.0.7 to the master branch version did the trick.

It seems the `load` function was introduced [here](https://github.com/CellProfiler/core/commit/d6a077d4df1a19591c3cba581fd98a5f7bb84615#diff-52ffb68077c5ec826591b3288793b893d094ff0abafcb6d5f06fd4b001b4208a
) on the 20th of January 2021, which happened after the last release came out on 21st November 2020 (cellprofiler-core version 4.0.7). We probably need a new release of cellprofiler-core, and then to bump the pinned version number in cellprofiler's `setup.py` file.

Now I can launch the main cellprofiler window! 
I do see a  bunch of errors relating to icons in the terminal (expand details for more info on those)

<details>
<summary>Details:</summary>

```
(cellprofiler-dev) genevieve@genevieve-G5-5500:~/GitHub/cellprofiler-core$ cellprofiler
Gtk-Message: 12:59:51.128: Failed to load module "atk-bridge"
Gtk-Message: 12:59:51.130: Failed to load module "canberra-gtk-module"
12:59:51: Debug: Adding duplicate image handler for 'Windows bitmap file'
12:59:51: Debug: Adding duplicate animation handler for '1' type
12:59:51: Debug: Adding duplicate animation handler for '2' type

(cellprofiler:30065): GLib-GIO-CRITICAL **: 12:59:52.183: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(cellprofiler:30065): Gtk-WARNING **: 12:59:52.183: Error loading theme icon 'edit-redo' for stock: Failed to load icon

(cellprofiler:30065): Gtk-CRITICAL **: 12:59:52.183: render_fallback_image: assertion 'pixbuf != NULL' failed

(cellprofiler:30065): GLib-GObject-CRITICAL **: 12:59:52.183: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(cellprofiler:30065): Gdk-WARNING **: 12:59:52.203: gdk_window_set_icon_list: icons too large
12:59:52: Debug: ClientToScreen cannot work when toplevel window is not shown

(cellprofiler:30065): Gdk-WARNING **: 12:59:52.268: gdk_window_set_icon_list: icons too large

(cellprofiler:30065): GLib-GIO-CRITICAL **: 12:59:52.271: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(cellprofiler:30065): Gtk-WARNING **: 12:59:52.271: Error loading theme icon 'dialog-question' for stock: Failed to load icon

(cellprofiler:30065): Gtk-CRITICAL **: 12:59:52.271: render_fallback_image: assertion 'pixbuf != NULL' failed

(cellprofiler:30065): GLib-GObject-CRITICAL **: 12:59:52.272: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(cellprofiler:30065): Gdk-WARNING **: 12:59:52.275: gdk_window_set_icon_list: icons too large

(cellprofiler:30065): GLib-GIO-CRITICAL **: 12:59:52.297: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(cellprofiler:30065): Gtk-WARNING **: 12:59:52.297: Error loading theme icon 'dialog-question' for stock: Failed to load icon

(cellprofiler:30065): Gtk-CRITICAL **: 12:59:52.297: render_fallback_image: assertion 'pixbuf != NULL' failed

(cellprofiler:30065): GLib-GObject-CRITICAL **: 12:59:52.297: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(cellprofiler:30065): GLib-GIO-CRITICAL **: 12:59:52.322: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(cellprofiler:30065): Gtk-WARNING **: 12:59:52.322: Error loading theme icon 'dialog-question' for stock: Failed to load icon

(cellprofiler:30065): Gtk-CRITICAL **: 12:59:52.322: render_fallback_image: assertion 'pixbuf != NULL' failed

(cellprofiler:30065): GLib-GObject-CRITICAL **: 12:59:52.322: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

```

</details>

**Comment by GenevieveBuckley** [comment]
Because I'll forget some of the details otherwise, [I've written up the process I had to do in this gist](https://gist.github.com/GenevieveBuckley/d17a94eac2293d0540d5881bc358dd6a) and have also uploaded a gist of my [exported conda environment](https://gist.github.com/GenevieveBuckley/38bf1679e97c5dec2a94d24efd59618a)

We can probably close this issue if you don't think the icon errors are something that needs fixing.

**Comment by GenevieveBuckley** [comment]
Closing this, since I'm all set to play around with some toy workflows from @bethac07 now :smile: 

Thanks for all the help!
