### ISSUE TITLE
CP4 is not working in headless mode with Python 3.8

### ISSUE THREAD

**Issue by orgonth** [CellProfiler/CellProfiler#4064]
When running CellProfiler in GUI-less mode, a couple of errors are encountered:
- When using `-i` option: `AttributeError: module 'ntpath' has no attribute 'walk'`
- When `--first-image-set` is not set

This behavior is not observed in CP 3. I will propose a PR to fix this issue.

**Comment by bmccartyjhu** [comment]
Adding on - I got it running by making the edits orgonth did, but did run into an issue in line 888-889 when trying to save data in a .mat format:

>    if len(args) > 0 and not use_hdf5:
        pipeline.save_measurements(args[0], measurements)

It seems that either (a) these couple of lines escaped deletion and a note that it only supports .hdf5 now should be made, or (b) this hasn't been updated to "cellprofiler_core.pipeline" (in which case the entire .mat/handles save code hasn't been transitioned yet either, as it all disappeared from the core.pipeline code)

**Comment by bethac07** [comment]
Matlab reading and writing will be deprecated in CP 4.0; sorry, we've had a deprecation warning on that since CP 3.0.0
